OrdererOrgs:
  - Name: Orderer
    Domain: crowdsensing.com

    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.crowdsensing.dmv.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 1

  - Name: Org2
    Domain: org2.crowdsensing.rsu.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 1

  - Name: Org3
    Domain: org3.crowdsensing.car.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 1
