OrdererOrgs:
  - Name: Orderer
    Domain: crowdsensing.com

    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.crowdsensing.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 2

  - Name: Org2
    Domain: org2.crowdsensing.com
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 2

