#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  default:
    
services:

  orderer.crowdsensing.com:
    container_name: orderer.crowdsensing.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    tty: true
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/crowdsensing.com/orderers/orderer.crowdsensing.com/:/etc/hyperledger/msp/orderer
    networks:
      default:
        aliases:
          - orderer.crowdsensing.com

  peer0.org1.crowdsensing.dmv.com:
    container_name: peer0.org1.crowdsensing.dmv.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer0.org1.crowdsensing.dmv.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org1.crowdsensing.dmv.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.crowdsensing.dmv.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=org1.crowdsensing.dmv.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.crowdsensing.dmv.com/peers/peer0.org1.crowdsensing.dmv.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer0.org1.crowdsensing.dmv.com

  peer1.org1.crowdsensing.dmv.com:
    container_name: peer1.org1.crowdsensing.dmv.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer1.org1.crowdsensing.dmv.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org1.crowdsensing.dmv.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.crowdsensing.dmv.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=org1.crowdsensing.dmv.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7151:7051
      - 7153:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.crowdsensing.dmv.com/peers/peer1.org1.crowdsensing.dmv.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer1.org1.crowdsensing.dmv.com

  peer0.org2.crowdsensing.rsu.com:
    container_name: peer0.org2.crowdsensing.rsu.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer0.org2.crowdsensing.rsu.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org2.crowdsensing.rsu.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.crowdsensing.rsu.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=org2.crowdsensing.rsu.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.crowdsensing.rsu.com/peers/peer0.org2.crowdsensing.rsu.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer0.org2.crowdsensing.rsu.com

  peer1.org2.crowdsensing.rsu.com:
    container_name: peer1.org2.crowdsensing.rsu.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer1.org2.crowdsensing.rsu.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org2.crowdsensing.rsu.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.crowdsensing.rsu.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=org2.crowdsensing.rsu.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8151:7051
      - 8153:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.crowdsensing.rsu.com/peers/peer1.org2.crowdsensing.rsu.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer1.org2.crowdsensing.rsu.com

  peer0.org3.crowdsensing.car.com:
    container_name: peer0.org3.crowdsensing.car.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer0.org3.crowdsensing.car.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org3.crowdsensing.car.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.crowdsensing.car.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=org3.crowdsensing.car.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org3.crowdsensing.car.com/peers/peer0.org3.crowdsensing.car.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer0.org3.crowdsensing.car.com

  peer1.org3.crowdsensing.car.com:
    container_name: peer1.org3.crowdsensing.car.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=crowdsensing
      - CORE_PEER_ID=peer1.org3.crowdsensing.car.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org3.crowdsensing.car.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.crowdsensing.car.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=org3.crowdsensing.car.com
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9151:7051
      - 9153:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org3.crowdsensing.car.com/peers/peer1.org3.crowdsensing.car.com/msp:/var/hyperledger/msp
    depends_on:
      - orderer.crowdsensing.com
    networks:
      default:
        aliases:
          - peer1.org3.crowdsensing.car.com

